export default {
  header: {
    headers: [
      { text: "작업지시코드", value: "code", width: "10%" },
      { text: "작업지시서명", value: "name" },
      { text: "회사", value: "customer.name" },
      { text: "상태", value: "status", width: "7%" },
      { text: "납기일", value: "deadline", width: "7%" },
      { text: "작성자", value: "createdName" },
      { text: "부서", value: "departmentName", width: "7%" },
      { text: "담당자", value: "chargeName" },
      { text: "수정자", value: "modifiedName" },
      { text: "수정일", value: "modifiedDate", width: "7%" },
      { text: "등록일", value: "createdDate", width: "7%" },
      { text: "상태변경", value: "changeOrder" },
      { text: "수정/삭제", value: "edit", width: "5%" },
    ],
    headersDetail: [
      { text: "작업지시코드", value: "code" },
      { text: "작업지시서명", value: "name" },
      { text: "회사", value: "customer.name" },
      { text: "상태", value: "status" },
      { text: "납기일", value: "deadline" },
      { text: "부서", value: "departmentName" },
      { text: "담당자", value: "chargeName" },
      { text: "수정자", value: "modifiedName" },
      { text: "수정일", value: "modifiedDate" },
      { text: "품목정보", value: "details" },
      { text: "작성자", value: "createdName" },
      { text: "등록일", value: "createdDate" },
      { text: "비고", value: "memo" },
    ],
    itemheaders: [
      { text: "타입", value: "type" },
      { text: "버전", value: "version" },
      { text: "품목코드", value: "code" },
      { text: "품목명", value: "name" },
      { text: "단위", value: "standard" },
      { text: "기준단위", value: "unit" },
    ],
    orderitemheaders: [
      { text: "납품예정일", value: "expectedDeliveryDate" },
      { text: "품목id", value: "itemId", align: " d-none" },
      { text: "수주품목", value: "itemName" },
      {
        text: "orderInfoDetailId",
        value: "orderInfoDetailId",
        align: " d-none",
      },
      { text: "수량", value: "quantity" },
      { text: "단가", value: "supplyUnitPrice" },
      { text: "비고", value: "memo" },
    ],
    register_itemheaders: [
      { text: "itemId", value: "itemId" },
      { text: "품목명", value: "itemName" },
      { text: "납품예정일", value: "expectedDeliveryDate", align: " d-none" },
      { text: "단가", value: "supplyUnitPrice", align: " d-none" },
    ],
    selectedheaders: [
      { text: "품목명", value: "itemName" },
      { text: "수량", value: "quantity", width: "10%" },
      { text: "단가", value: "supplyUnitPrice", width: "10%" },
      { text: "납품예정일", value: "expectedDeliveryDate", width: "20%" },
      { text: "비고", value: "memo", width: "30%" },
      { text: "삭제", value: "delete", width: "10%" },
    ],
    tempheader: [
      { text: "작업지시서명", value: "name" },
      { text: "거래처", value: "customer.name" },
      { text: "납기일", value: "deadline" },
      { text: "부서", value: "departmentName" },
      { text: "담당자", value: "chargeName" },
      { text: "품목정보", value: "details" },
      { text: "비고", value: "memo" },
      { text: "등록일", value: "createdDate" },
      { text: "삭제", value: "edit" },
    ],
    totalItem: [
      { text: "버전", value: "itemVersion" },
      { text: "원자재명", value: "itemName" },
      { text: "개수", value: "count" },
    ],
  },
};
