export default {
  header: {
    headers_Detail: [
      { text: "품목코드", value: "itemCode" },
      { text: "품목명", value: "itemName" },
      { text: "타입", value: "itemType" },
      { text: "상태", value: "status" },
      { text: "투입수량", value: "targetCount" },
      { text: "담당자", value: "createdId" },
      { text: "등록일", value: "createdDate" },
      { text: "수정자", value: "modifiedId" },
      { text: "수정일자", value: "modifiedDate" },
      { text: "진행", value: "work" },
    ],
    headers_Details_Details: [
      { text: "거래처", value: "customer" },
      { text: "마감일", value: "deadLine" },
      { text: "품목코드", value: "itemCode" },
      { text: "품목명", value: "itemName" },
      { text: "작업지시서 코드", value: "jobOrderCode" },
      { text: "상태", value: "status" },
      { text: "진행", value: "work" },
      { text: "상세", value: "detail" },
    ],
    detail_jobOrder: [
      { text: "작업지시코드", value: "code", width: "13%", sortable: false },
      { text: "작업지시서명", value: "name", width: "10%", sortable: false },
      { text: "거래처", value: "customer", width: "10%", sortable: false },
      { text: "상태", value: "status", width: "2%", sortable: false },
      { text: "납기일", value: "deadline", width: "12%", sortable: false },
      { text: "작성자", value: "createdId", width: "5%", sortable: false },
      { text: "수정자", value: "modifiedId", width: "5%", sortable: false },
      { text: "수정일", value: "modifiedDate", width: "7%", sortable: false },
      { text: "등록일", value: "createDate", width: "7%", sortable: false },
      { text: "타입", value: "type", width: "7%", sortable: false },
      { text: "목표수량", value: "targetCount", width: "7%", sortable: false },
      // { text: "상태변경", value: "changeOrder" },
    ],
  },
  data: {
    status_JO: [
      { code: "SA01", name: "대기" },
      { code: "SA02", name: "진행중" },
      { code: "SA03", name: "완료" },
    ],
    status_JOD: [
      { code: "SB01", name: "준비" },
      { code: "SB02", name: "파종" },
      { code: "SB03", name: "발아" },
      { code: "SB04", name: "1차육묘" },
      { code: "SB05", name: "접목" },
      { code: "SB06", name: "활착" },
      { code: "SB07", name: "2차육묘" },
      { code: "SB08", name: "완료" },
    ],
    status2: [
      { code: "대기", name: "대기" },
      { code: "작업 진행중", name: "작업 진행중" },
      { code: "생산 완료", name: "생산 완료" },
      { code: "완료", name: "완료" },
    ],
  },
};
