export default {
  data: {
    monitorData: [
      //5.외부센서,측정값
      {
        num: 1,
        roomName: "발아실",
        Temperature: 0,
        Humidity: 0,
        unit: "kWh/m2",
        fan: "",
        LED: "",
        humidifier: "",
        temp_unit: "°C",
        humidity_unit: "%",
      },
      {
        num: 2,
        roomName: "1차 육묘실",
        Temperature: 0,
        Humidity: 0,
        unit: "kWh/m2",
        fan: "OFF",
        LED: "OFF",
        humidifier: "OFF",
      },
      {
        num: 3,
        roomName: "2차 육묘실",
        Temperature: 0,
        Humidity: 0,
        unit: "kWh/m2",
        fan: "OFF",
        LED: "OFF",
        humidifier: "OFF",
      },

      {
        num: 4,
        roomName: "활착실1",
        Temperature: 0,
        Humidity: 0,
        unit: "kWh/m2",
        fan: "OFF",
        LED: "OFF",
        humidifier: "OFF",
      },

      {
        num: 5,
        roomName: "활착실2",
        Temperature: 0,
        Humidity: 0,
        unit: "kWh/m2",
        fan: "OFF",
        LED: "OFF",
        humidifier: "OFF",
      },

      {
        num: 6,
        roomName: "활착실3",
        Temperature: 0,
        Humidity: 0,
        unit: "kWh/m2",
        fan: "OFF",
        LED: "OFF",
        humidifier: "OFF",
      },
    ],
    windDirectionData: [
      { val: 0, DI: "N" },
      { val: 1, DI: "NNE" },
      { val: 2, DI: "NE" },
      { val: 3, DI: "ENE" },
      { val: 4, DI: "E" },
      { val: 5, DI: "ESE" },
      { val: 6, DI: "SE" },
      { val: 7, DI: "SSE" },
      { val: 8, DI: "S" },
      { val: 9, DI: "SSW" },
      { val: 10, DI: "SW" },
      { val: 11, DI: "WSW" },
      { val: 12, DI: "W" },
      { val: 13, DI: "WNW" },
      { val: 14, DI: "NW" },
      { val: 15, DI: "NNW" },
      { val: 16, DI: "N" },
    ],
  },
};
