export default {
  header: {
    headers: [
      { text: "작업지시코드", value: "code", width: "10%" },
      { text: "작업지시서명", value: "name" },
      { text: "회사", value: "customer.name" },
      { text: "상태", value: "status", width: "7%" },
      { text: "납기일", value: "deadline", width: "7%" },
      { text: "작성자", value: "createdName" },
      { text: "부서", value: "departmentName", width: "7%" },
      { text: "담당자", value: "chargeName" },
      { text: "수정자", value: "modifiedName" },
      { text: "수정일", value: "modifiedDate", width: "7%" },
      { text: "등록일", value: "createdDate", width: "7%" },
      { text: "상태변경", value: "changeOrder" },
      { text: "수정/삭제", value: "edit", width: "5%" },
    ],
    headersDetail: [
      { text: "작업지시코드", value: "code" },
      { text: "작업지시서명", value: "name" },
      { text: "회사", value: "customer.name" },
      { text: "상태", value: "status" },
      { text: "납기일", value: "deadline" },
      { text: "부서", value: "departmentName" },
      { text: "담당자", value: "chargeName" },
      { text: "수정자", value: "modifiedName" },
      { text: "수정일", value: "modifiedDate" },
      { text: "품목정보", value: "details" },
      { text: "작성자", value: "createdName" },
      { text: "등록일", value: "createdDate" },
      { text: "비고", value: "memo" },
    ],
    itemheaders: [
      { text: "타입", value: "type" },
      { text: "버전", value: "version" },
      { text: "품목코드", value: "code" },
      { text: "품목명", value: "name" },
      { text: "단위", value: "standard" },
      { text: "기준단위", value: "unit" },
    ],
    orderitemheaders: [
      { text: "납품예정일", value: "expectedDeliveryDate" },
      { text: "품목id", value: "itemId", align: " d-none" },
      { text: "수주품목", value: "itemName" },
      {
        text: "orderInfoDetailId",
        value: "orderInfoDetailId",
        align: " d-none",
      },
      { text: "수량", value: "quantity" },
      { text: "단가", value: "supplyUnitPrice" },
      { text: "비고", value: "memo" },
    ],
    register_itemheaders: [
      { text: "itemId", value: "itemId", align: " d-none" },
      { text: "품목명", value: "itemName" },
      { text: "납품예정일", value: "expectedDeliveryDate", align: " d-none" },
      { text: "단가", value: "supplyUnitPrice", align: " d-none" },
    ],
    selectedheaders: [
      { text: "품목명", value: "itemName", width: "10%" },
      { text: "수량", value: "quantity", width: "5%" },
      { text: "단가", value: "supplyUnitPrice", width: "10%" },
      { text: "납품예정일", value: "expectedDeliveryDate", width: "10%" },
      { text: "비고", value: "memo", width: "15%" },
      { text: "삭제", value: "delete", width: "2%" },
    ],
    tempheader: [
      { text: "작업지시서명", value: "name" },
      { text: "거래처", value: "customer.name" },
      { text: "납기일", value: "deadline" },
      { text: "부서", value: "departmentName" },
      { text: "담당자", value: "chargeName" },
      { text: "품목정보", value: "details" },
      { text: "비고", value: "memo" },
      { text: "등록일", value: "createdDate" },
      { text: "삭제", value: "edit" },
    ],
    totalItem: [
      { text: "버전", value: "itemVersion" },
      { text: "원자재명", value: "itemName" },
      { text: "개수", value: "count" },
    ],
    customerList: [
      { text: "code", value: "code" },
      { text: "거래처", value: "name" },
      { text: "연락처", value: "contactPoint" },
      { text: "담당자", value: "manager" },
      { text: "생성일자", value: "createdDate" },
      { text: "생성한 ID", value: "createdId" },
      { text: "수정일자", value: "modifiedDate" },
      { text: "수정한 ID", value: "modifiedId" },
      { text: "수정", value: "edit" },
    ],
    orderList: [
      { text: "수주일자", value: "orderDate", width: "10%" },
      { text: "수주번호", value: "orderInfoCode", width: "15%" },
      { text: "거래처", value: "customerName", width: "15%" },
      { text: "요청사항 (클릭해서 수정하기) ", value: "memo", width: "30%" },
      { text: "상세수정", value: "edit", width: "5%" },
      { text: "삭제", value: "delete", width: "3%" },
    ],
  },
  data: {
    search_list1: [
      { name: "거래처명", value: 1 },
      { name: "거래처코드", value: 2 },
      { name: "담당자", value: 3 },
      { name: "담당자연락처", value: 4 },
      { name: "거래처명", value: 5 },
    ],
    search_list2: [
      { name: "사업자 등록번호", value: 1 },
      { name: "대표자", value: 2 },
      { name: "업태", value: 3 },
      { name: "업종", value: 4 },
      { name: "거래처 주소", value: 5 },
      { name: "거래처 영어주소", value: 6 },
      { name: "거래처 이메일", value: 7 },
      { name: "거래처 회사번호", value: 8 },
      { name: "거래처 팩스번호", value: 9 },
    ],
    search_list3: [
      { name: "전체", value: "" },
      { name: "사용", value: "사용" },
      { name: "미사용", value: "미사용" },
    ],
    search_list4: [
      { name: "사용", value: "사용" },
      { name: "미사용", value: "미사용" },
    ],
    customer_type: [
      { name: "전체", value: "" },
      { name: "매입거래처", value: "매입거래처" },
      { name: "매출거래처", value: "매출거래처" },
      { name: "병합거래처", value: "병합거래처" },
      { name: "기타거래처", value: "기타거래처" },
    ],
  },
};
